### ISSUE TITLE
Entitlements.plist missing and mkdir fails

### ISSUE THREAD

**Issue by lukas-kyeso** [UNSH/Unity-Apple-Distribution-Workflow#1]
Firstly, this is an absolutely amazing effort and I am super thankful to you for creating this! And I'm sure whoever next tries to build for Mac will also be!

2 minor issues:
The SignAndPackage script looks for "Entitlements.plist", but the file is called "entitlements.plist".
The SignAndPackage script tries to mkfile but there is are no folders Appstore/Development and Appstore/Distribution and /Outside appstore so it crashes.

Otherwise works wonderfully!

**Comment by UNSH** [comment]
Hey Lukas, 
Thanks for heads up and your comment. I’m currently on holiday and I only have my phone. I basically created the folder structure and renamed the entitlements file. I don’t want to dig in the code on my phone as that’s a recipe for disaster :) Could you maybe check if everything works now with the latest build?
